name: Propose to Investigate
description: Technology that is being investigated prior to any trial
title: '[INVESTIGATE] ...'
labels:
  - Investigate

body:
  - type: dropdown
    id: category
    attributes:
      label: Proposal Category
      multiple: false
      options:
        - Langauges and Frameworks
        - Techniques
        - Tools
        - Platforms

  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: What does the technology do? What problems should it solve

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links. Costs.

  - type: textarea
    id: refs
    attributes:
      label: References
      description: Links. Resources. Related issues/proposals
